// mf-b/src/app/components/ItemRow.tsx
import { useState } from 'react';
import { Item } from '../item.model';
import './ItemRow.css';

interface ItemRowProps {
  item: Item;
  onUpdate: (id: number, name: string) => void;
  onRemove: (id: number) => void;
}

export function ItemRow({ item, onUpdate, onRemove }: ItemRowProps) {
  const [editing, setEditing] = useState<boolean>(false);
  const [draft, setDraft] = useState<string>(item.name);

  const startEdit = (): void => {
    setDraft(item.name);
    setEditing(true);
  };

  const cancelEdit = (): void => {
    setEditing(false);
    setDraft(item.name);
  };

  const saveEdit = (): void => {
    const trimmed = draft.trim();
    if (!trimmed || trimmed.length > 50) {
      return;
    }
    onUpdate(item.id, trimmed);
    setEditing(false);
  };

  return (
    <li className="item-row">
      <span className="item-row__id">#{item.id}</span>
      {editing ? (
        <input
          className="item-row__input"
          type="text"
          maxLength={50}
          value={draft}
          onChange={(event) => setDraft(event.target.value)}
        />
      ) : (
        <span className="item-row__name">{item.name}</span>
      )}
      <div className="item-row__actions">
        {editing ? (
          <>
            <button
              className="item-row__btn item-row__btn--save"
              type="button"
              onClick={saveEdit}
              disabled={!draft.trim() || draft.trim().length > 50}
            >
              Save
            </button>
            <button
              className="item-row__btn item-row__btn--cancel"
              type="button"
              onClick={cancelEdit}
            >
              Cancel
            </button>
          </>
        ) : (
          <>
            <button
              className="item-row__btn item-row__btn--edit"
              type="button"
              onClick={startEdit}
            >
              Edit
            </button>
            <button
              className="item-row__btn item-row__btn--remove"
              type="button"
              onClick={() => onRemove(item.id)}
            >
              Delete
            </button>
          </>
        )}
      </div>
    </li>
  );
}

// mf-a/src/app/item-row/item-row.component.ts
import { Component, input, output, signal, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Item } from '../item.model';

@Component({
  selector: 'app-item-row',
  imports: [FormsModule],
  templateUrl: './item-row.component.html',
  styleUrl: './item-row.component.css',
})
export class ItemRowComponent {
  readonly item = input.required<Item>();
  readonly remove = output<number>();
  readonly edit = output<{ id: number; name: string }>();

  protected readonly editing = signal(false);
  protected readonly draft = signal('');
  protected readonly maxLength = 50;

  protected startEdit(): void {
    this.draft.set(this.item().name);
    this.editing.set(true);
  }

  protected cancelEdit(): void {
    this.editing.set(false);
    this.draft.set('');
  }

  protected saveEdit(): void {
    const value = this.draft().trim();
    if (!value || value.length > this.maxLength) {
      return;
    }
    this.edit.emit({ id: this.item().id, name: value });
    this.editing.set(false);
  }

  protected onRemove(): void {
    this.remove.emit(this.item().id);
  }
}

<li class="item-row">
  <span class="id">#{{ item().id }}</span>
  @if (editing()) {
    <input
      type="text"
      [ngModel]="draft()"
      (ngModelChange)="draft.set($event)"
      [maxlength]="maxLength"
      name="draft"
    />
    <div class="actions">
      <button type="button" class="save" (click)="saveEdit()">Guardar</button>
      <button type="button" class="cancel" (click)="cancelEdit()">Cancelar</button>
    </div>
  } @else {
    <span class="name">{{ item().name }}</span>
    <div class="actions">
      <button type="button" class="edit" (click)="startEdit()">Editar</button>
      <button type="button" class="delete" (click)="onRemove()">Eliminar</button>
    </div>
  }
</li>
